### ISSUE TITLE
TemplateLookup is not working correctly in namespaces/includes tags.  

### ISSUE THREAD

**Issue by diffore** [sqlalchemy/mako#294]
Hi, 
I had a problem with the TemplateLookup/Template mechanism not working properly when templates are located in other folder. See example below: 

Project file structure:  
_main.py 
templates_folder/some_include.txt
templates_folder/main.txt_

**main.py**: 
#!/usr/bin/python3
from mako.template import Template
from mako.lookup import TemplateLookup
import os

path_to_templates = os.path.dirname(os.path.realpath(__file__)) + os.sep + 'templates_folder' + os.sep)  # template folder always near the script itself
mylookup = TemplateLookup(directories=[path_to_templates])
main_template = Template(filename=path_to_templates + os.sep + 'main.txt', lookup=mylookup)
print(main_template.render())

**templates_folder/main.txt** :
<%namespace file="some_include.txt" import="some_func"/>
hello world

==================================================================
Running main.py is causing the following big error stack: 
Traceback (most recent call last):
  File "_home_diffore_Documents_TEST_templates_folder__main_txt", line 17, in _mako_get_namespace
KeyError: ('_home_diffore_Documents_TEST_templates_folder__main_txt', '__anon_0x7f0884416630')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diffore/.local/lib/python3.6/site-packages/mako/lookup.py", line 247, in get_template
    return self._check(uri, self._collection[uri])
KeyError: '/home/diffore/Documents/TEST/templates_folder/some_include.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diffore/.local/lib/python3.6/site-packages/mako/runtime.py", line 802, in _lookup_template
    return lookup.get_template(uri)
  File "/home/diffore/.local/lib/python3.6/site-packages/mako/lookup.py", line 261, in get_template
    "Cant locate template for uri %r" % uri)
mako.exceptions.TopLevelLookupException: Cant locate template for uri '/home/diffore/Documents/TEST/templates_folder/some_include.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    print(main_template.render())
  File "/home/diffore/.local/lib/python3.6/site-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/diffore/.local/lib/python3.6/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/diffore/.local/lib/python3.6/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/diffore/.local/lib/python3.6/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "_home_diffore_Documents_TEST_templates_folder__main_txt", line 30, in render_body
  File "_home_diffore_Documents_TEST_templates_folder__main_txt", line 19, in _mako_get_namespace
  File "_home_diffore_Documents_TEST_templates_folder__main_txt", line 22, in _mako_generate_namespaces
  File "/home/diffore/.local/lib/python3.6/site-packages/mako/runtime.py", line 560, in __init__
    calling_uri)
  File "/home/diffore/.local/lib/python3.6/site-packages/mako/runtime.py", line 804, in _lookup_template
    raise exceptions.TemplateLookupException(str(compat.exception_as()))
mako.exceptions.TemplateLookupException: Cant locate template for uri '/home/diffore/Documents/TEST/templates_folder/some_include.txt'

==================================================================

Path in error message: _/home/diffore/Documents/TEST/templates_folder/some_include.txt_  is correct and file is available for reading.  From what I managed to debug, the inner _collection dict is empty which is causing the error message. 

I've overcome the issue by filling the _collection dict manually using put_template method, but I think it is supposed to be working automatically. 

Can you please check?  Debugging this was very problematic :)

**Comment by zzzeek** [comment]
hi there -

I would advise against using Template() directly when you have a real file and the TemplateLookup already.   This script is kind of confusing, but in general if you want includes to work the template needs to have a uri:

```
main_template = Template(
    filename=path_to_templates + os.sep + "main.txt",
    uri="main.txt",
    lookup=mylookup
)



```

hope this helps

**Comment by diffore** [comment]
Thank you for the reply. 

I think we have overthinked this a little and, as you said, it is easier to just use TemplateLookup only.
