### ISSUE TITLE
Uses time.clock() on Windows which is gone with Python 3.8

### ISSUE THREAD

**Issue by lazka** [sqlalchemy/mako#301]
https://github.com/sqlalchemy/mako/blob/4f8dae914dd8e05dffaeea35c68694871cd7b8fc/mako/compat.py#L145

```python
Traceback (most recent call last):
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\pyperformance\benchmarks\bm_mako.py", line 20, in <module>
    from mako.template import Template   # noqa
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\template.py", line 10, in <module>
    from mako.lexer import Lexer
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\lexer.py", line 11, in <module>
    from mako import parsetree, exceptions, compat
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\parsetree.py", line 9, in <module>
    from mako import exceptions, ast, util, filters, compat
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\exceptions.py", line 11, in <module>
    from mako import util, compat
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\util.py", line 11, in <module>
    from mako import compat
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\compat.py", line 123, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'
```

Using `timeit.default_timer()` instead would work as far as I can see.

**Comment by zzzeek** [comment]
can we deprecate windows ? :)  haha.   OK, first I'm seeing about "default_timer" but it's documetned as always "perf_counter()" and in 3.3 on above.  Can we use perf_counter() on all platforms ?

**Comment by zzzeek** [comment]
also are you available to send a PR using perf_counter() for Python 3.3 and above ?  it would help a lot.

**Comment by lazka** [comment]
Sure -> #302

**Comment by sqla-tester** [comment]
**Christoph Reiter** has proposed a fix for this issue in the **master** branch:

**compat: use timeit.default_timer instead of time.clock which is gone in Python 3.8** https://gerrit.sqlalchemy.org/1377

**Comment by sqla-tester** [comment]
**Christoph Reiter** has proposed a fix for this issue in the **master** branch:

**use timeit.default_timer instead of time.clock() / time.time()** https://gerrit.sqlalchemy.org/1377
